---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: yes
  
  roles:
    - { role: geerlingguy.repo-epel }
    - { role: geerlingguy.nodejs }
    - { role: wetty }

  tasks:
    - name: Enable RHEL Extras Repo
      yum_repository: 
        name: rhui-REGION-rhel-server-extras
        mirrorlist: https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/$releasever/$basearch/extras/os
        enabled: yes

    - name: Create Workshop User
      user:
        name:      "{{ workshop_user }}"
        password:  "{{ workshop_password |password_hash('sha512') }}"
        shell: /bin/bash
        groups: 
          - wheel
        append:    yes
        state:     present

