---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: yes
  
  roles:
    - { role: geerlingguy.repo-epel }
    - { role: geerlingguy.nodejs }
    - { role: wetty }

  tasks:
    - name: Enable RHEL Extras Repo
      yum_repository: 
        name: rhui-REGION-rhel-server-extras
        description: RHEL Extras Repo
        mirrorlist: https://rhui2-cds01.REGION.aws.ce.redhat.com/pulp/mirror/content/dist/rhel/rhui/server/7/$releasever/$basearch/extras/os
        enabled: yes

    - name: Create Workshop User
      user:
        name:      "{{ workshop_user }}"
        password:  "{{ workshop_password |password_hash('sha512') }}"
        shell: /bin/bash
        groups: 
          - wheel
        append:    yes
        state:     present

    - name: Install OpenShift Client
      unarchive:
        src:  https://github.com/openshift/origin/releases/download/v3.9.0/openshift-origin-client-tools-v3.9.0-191fece-linux-64bit.tar.gz
        dest: /usr/bin/
        remote_src: yes
        extra_opts: [--strip-components=1]
