---
- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: true
  become: yes
  
  roles:
    - { role: geerlingguy.repo-epel }
    - { role: geerlingguy.nodejs }
    - { role: wetty }

  tasks:
    - name: Enable RHEL Extras Repo
      command: yum-config-manager --enable rhui-REGION-rhel-server-extras
      when: ! yum repolist rhui-REGION-rhel-server-extras

    - name: Create Workshop User
      user:
        name:      "{{ workshop_user }}"
        password:  "{{ workshop_password |password_hash('sha512') }}"
        shell: /bin/bash
        groups: 
          - wheel
        append:    yes
        state:     present

